"""
This type stub file was generated by pyright.
"""

from typing import AsyncGenerator

class AbstractSampler:
    @abc.abstractmethod
    async def sample(self, messages: list[dict[str, str]]) -> AsyncGenerator[str, None]:
        ...
    


