"""
This type stub file was generated by pyright.
"""

from deeptools.samplers.abstract import AbstractSampler
from typing import AsyncGenerator

class LiteLLMSampler(AbstractSampler):
    def __init__(self, model_name: str, max_output=...) -> None:
        ...
    
    async def sample(self, messages: list[dict[str, str]]) -> AsyncGenerator[str, None]:
        ...
    


