"""
This type stub file was generated by pyright.
"""

from smolagents import Tool

class CompanyFinancialsTool(Tool):
    name = ...
    description = ...
    inputs = ...
    output_type = ...
    def __init__(self, cutoff_date=...) -> None:
        """
        Initialize the tool with a cutoff date.
        
        Args:
            cutoff_date: A string in format 'YYYY-MM-DD' or datetime object. 
                         If provided, will prevent fetching data beyond this date.
        """
        ...
    
    def forward(self, ticker: str, statement_type: str, period: str):
        ...
    


class StockPriceTool(Tool):
    name = ...
    description = ...
    inputs = ...
    output_type = ...
    def __init__(self, cutoff_date=...) -> None:
        """
        Initialize the tool with a cutoff date.
        
        Args:
            cutoff_date: A string in format 'YYYY-MM-DD' or datetime object. 
                         If provided, will prevent fetching data beyond this date.
        """
        ...
    
    def forward(self, ticker: str, start_date: str, end_date: str, interval: str = ...):
        ...
    


