"""
This type stub file was generated by pyright.
"""

class TestVLLMClientServerTP:
    def __init__(self, model_id: str = ...) -> None:
        ...
    
    async def test_generate(self): # -> None:
        ...
    
    def test_update_model_params(self): # -> None:
        ...
    
    def test_reset_prefix_cache(self): # -> None:
        ...
    


