"""
This type stub file was generated by pyright.
"""

class TestToolCaller:
    def __init__(self, vllm_model_id: str) -> None:
        ...
    
    async def test_litellm_toolcaller(self): # -> None:
        ...
    
    async def test_vllm_toolcaller(self): # -> None:
        ...
    


