"""
This type stub file was generated by pyright.
"""

from deeptools.samplers.abstract import AbstractSampler
from smolagents import Tool

class ToolCaller:
    def __init__(self, sampler: AbstractSampler, system_prompt: str = ..., authorized_imports: list[str] = ...) -> None:
        ...
    
    async def generate(self, user_prompt: str, tools: list[Tool] = ...): # -> Generator[str | Any, Any, None]:
        ...
    


