"""
This type stub file was generated by pyright.
"""

from typing import AsyncGenerator
from deeptools.samplers.abstract import AbstractSampler

def setup_env(): # -> None:
    ...

class VLLMSampler(AbstractSampler):
    def __init__(self, model_id: str, max_output=...) -> None:
        ...
    
    async def sample(self, messages: list[dict[str, str]]) -> AsyncGenerator[str, None]:
        ...
    


